yyusupovSalesforceProject1/src/objects/Webinar__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Registration Open</fullName>
                </value>
                <value>
                    <fullName>Registration Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

yyusupovSalesforceProject1/src/classes/US106WebinarApproveRejectCtrlr.cls
/**
 * Created by yyusupov on 08.07.2022.
 */

public with sharing class US106WebinarApproveRejectCtrlr {
        @AuraEnabled
        public static Webinar__c[] getWebinars(Integer queryLimit){
            return [SELECT Type__c,Name,Status__c, Approval_Status__c, Cost__c FROM Webinar__c WHERE
                    Approval_Status__c = 'Pending' LIMIT :queryLimit];
    }

    @AuraEnabled
    public static void changeApprovalStatus(Id webinarId, String newStatus){
        Webinar__c webinar = [SELECT Id FROM Webinar__c WHERE Id = :webinarId];
        webinar.Approval_Status__c = newStatus;
        update webinar;
    }

    @AuraEnabled
    public static void assignRejectReason(Id webinarId, String reason){
        Webinar__c webinar = [SELECT Id FROM Webinar__c WHERE Id = :webinarId];
        webinar.Description__c = reason;
        update webinar;
    }

}