yyusupovSalesforceProject1/src/objects/Webinar__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <defaultValue>&quot;Pending&quot;</defaultValue>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Registration Open</fullName>
                </value>
                <value>
                    <fullName>Registration Closed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

yyusupovSalesforceProject1/src/classes/US107WebinarSearchComponentCtrlr.cls
/**
 * Created by yyusupov on 11.07.2022.
 */

public with sharing class US107WebinarSearchComponentCtrlr {
    @AuraEnabled
    public static Webinar__c[] getWebinars(){
        System.debug('test from get webinars');
        return [SELECT Type__c,Name,Status__c, Approval_Status__c, Cost__c FROM Webinar__c LIMIT 50];
    }

    @AuraEnabled
    public static Webinar__c[] getWebinarsByType(String type){
        return [SELECT Type__c,Name,Status__c, Approval_Status__c, Cost__c FROM Webinar__c WHERE
                Type__c LIKE :type LIMIT 50];
    }

    @AuraEnabled
    public static Webinar__c[] getWebinarsByStatus(String status){
        System.debug('before return');
        System.debug(status);

        return [SELECT Type__c,Name,Status__c, Approval_Status__c, Cost__c FROM Webinar__c WHERE
                Status__c LIKE :status  LIMIT 50];
    }

    @AuraEnabled
    public static void registerForWebinar(Id webinarId){
        Id currentUserId = UserInfo.getUserId();
        Webinar_Member__c webinarMember = new Webinar_Member__c(Related_User__c = currentUserId,
                Related_Webinar__c = webinarId);
//        Database.insert(webinarMember, false);
        insert webinarMember;
    }
}