yuldash.yusupovSFConnection/src/objects/Collections__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Collections</label>
    <nameField>
        <label>Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

yuldash.yusupovSFConnection/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Collection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collection</label>
        <referenceTo>Collections__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

yuldash.yusupovSFConnection/src/classes/CollectionTriggerHandler.cls
/**
 * Created by yyusupov on 22.07.2022.
 */

public with sharing class CollectionTriggerHandler {
    public static void handleAfterUpdate(List<Collections__c> newCollections){
        withdrawnCollectionProductsDeactivated(newCollections);
    }



    private static void withdrawnCollectionProductsDeactivated(List<Collections__c> newCollections){
        List<Id> collectionIds = new List<Id>();
        for (Collections__c collection : newCollections){
            if (collection.Status__c == 'Withdrawn'){
                collectionIds.add(collection.Id);
            }
        }

        List<Product2> relatedProducts = [SELECT IsActive FROM Product2 WHERE Collection__c IN :collectionIds];
        for (Product2 product : relatedProducts){
            product.IsActive = false;
        }

        update relatedProducts;
    }
}